/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Fibonacci.Sequence;

public class App {
    public static void main(String[] args){
        int t = 10;
        System.out.println("Nonrecursive: " + nonRecursive(t,0,1));
        System.out.println("Recursive: " + recursive(t));
    }
    public static int nonRecursive(int n,int a,int b){
        int next = 0;
        for(int i = 0;i < n;i++){
            next=a+b;
            a=b;
            b=next;
        }
        return next;
    }
    public static int recursive(int n){
        if (n>1){
            return recursive(n-1)+recursive(n-2);
        }else{
            return 1;
        }
    }
}
